### ISSUE TITLE
DNS error?

### ISSUE THREAD

**Issue by lukemac77** [keybuk/homebridge-powerview#10]
I recently started getting this error out of the blue:

`[PowerView] Cached shade 34693: Living Room Shade
[PowerView] Error getting userdata: Error: getaddrinfo ENOTFOUND powerview-hub.local powerview-hub.local:80
[PowerView] Error getting shades: Error: getaddrinfo ENOTFOUND powerview-hub.local powerview-hub.local:80`

When I ping powerview-hub.local, the appropriate response is received. Nothing else in my setup has changed and I have restarted the pi and restarted HomeBridge a number of times.

Any suggestions?

**Comment by keybuk** [comment]
Try rebooting the PowerView hub.

Otherwise if your home network has DNS issues, try using the IP address of the hub instead
