### ISSUE TITLE
Unknown type 6 - Roller Shades

### ISSUE THREAD

**Issue by eabakker** [keybuk/homebridge-powerview#12]
Using the Luxaflex Duette shades (top down only) in Europe. Gen 2 hub only recently released here.
Not sure if this causes the issue.

**Comment by keybuk** [comment]
You can make the warning go away with forceRollerShades as described in the README, but it should be otherwise fine as that's the default

**Comment by eabakker** [comment]
That works.

Other question, if I use the remote (pebble), the correct state of the shades is not showing in Homekit. So in homekit it says blind are closed, while they are actually open.

Erik

**Comment by eabakker** [comment]
Thanks for the yuck update :-)
 Cannot recall seeing it in the reader file, how do I enable the checking?

**Comment by keybuk** [comment]
Set "refreshShades" to true in the config

**Comment by keybuk** [comment]
I recommend using the new built-in HomeKit support
