### ISSUE TITLE
PowerView now natively supports HomeKit

### ISSUE THREAD

**Issue by khit** [keybuk/homebridge-powerview#16]
Big news in the PowerView iOS app version 2.4: https://cdn2.hunterdouglas.com/static/static/pdf/powerview-app-apple-homekit-guide.pdf

So far it’s working well on my setup. 

Thanks for all the work on the HomeBridge plugin while we waited on HD, keybuk!

**Comment by keybuk** [comment]
I haven't been able to get this to work at all

**Comment by khit** [comment]
> I haven't been able to get this to work at all

@keybuk I had to go through the setup 2x. Before attempt #2 I unplugged the PowerView Hub (make sure it is Gen 2 - you can verify by looking at the hub in the PowerView iOS app) and did a force quite on Apple's Home app. The hub went through an update (displayed a red light for a few minutes) after recycling the power. I'm assuming that's what allowed it to be added to HomeKit as a native hub. The other thing I did before my second attempt was remove homebridge-powerview from HomeBridge and delete the HB's cache files before restarting it. Hope you can get it working!

**Comment by keybuk** [comment]
After a bunch of resetting and rebooting, I got the new HomeKit support to work - and it works great!
