### ISSUE TITLE
Gen 1 Hub: TypeError:Cannot read property 'mainProcessor' of undefined

### ISSUE THREAD

**Issue by samwelnella** [keybuk/homebridge-powerview#3]
I have a Gen 1 hub and I'm getting the following error when trying to use this plugin:

`Apr 24 13:10:15 nuc-homebridge homebridge[28523]: /usr/lib/node_modules/homebridge-powerview/index.js:328
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:                         this.hubVersion = userData.firmware.mainProcessor.name;
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:                                        ^
Apr 24 13:10:15 nuc-homebridge homebridge[28523]: TypeError: Cannot read property 'mainProcessor' of undefined
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at PowerViewPlatform.<anonymous> (/usr/lib/node_modules/homebridge-powerview/index.js:328:40)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at PowerViewHub.<anonymous> (/usr/lib/node_modules/homebridge-powerview/PowerViewHub.js:84:18)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at Request.self.callback (/usr/lib/node_modules/homebridge-powerview/node_modules/request/request.js:186:22)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at Request.emit (events.js:180:13)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-powerview/node_modules/request/request.js:1163:10)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at Request.emit (events.js:180:13)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-powerview/node_modules/request/request.js:1085:12)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at Object.onceWrapper (events.js:272:13)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at IncomingMessage.emit (events.js:185:15)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at endReadableNT (_stream_readable.js:1106:12)
Apr 24 13:10:15 nuc-homebridge homebridge[28523]:     at process._tickCallback (internal/process/next_tick.js:178:19)`

**Comment by keybuk** [comment]
Thanks for trying out the plugin!

I'm still developing it at the moment, and I have a Gen 2 hub here, so I would need a little help to make it work with the Gen 1, if you're willing?

Can you run the following two commands for me (replacing the hostname with your hub's, or your hub IP, if appropriate), and attach the output:

```
curl http://powerview-hub.local/api/userdata
```
```
curl http://powerview-hub.local/api/shades
```

Thanks!

**Comment by samwelnella** [comment]
Thanks for your help. Here's the

`curl http://powerview-hub.local/api/userdata`
`{"userData":{"serialNumber":"REDACTED","rfID":"0xEACD","rfIDInt":60109,"rfStatus":0,"hubName":"SG9tZQ==","macAddress":"REDACTED","roomCount":6,"shadeCount":10,"groupCount":8,"sceneCount":13,"sceneMemberCount":25,"multiSceneCount":1,"multiSceneMemberCount":4,"scheduledEventCount":3,"sceneControllerCount":0,"sceneControllerMemberCount":0,"accessPointCount":2,"localTimeDataSet":true,"enableScheduledEvents":false,"remoteConnectEnabled":false,"editingEnabled":true,"setupCompleted":false,"gateway":"172.16.0.1","mask":"255.255.255.0","ip":"172.16.0.195","dns":"172.16.0.250","staticIp":false,"addressKind":"newPrimary","unassignedShadeCount":0,"undefinedShadeCount":0}}`

`curl http://powerview-hub.local/api/shades`
`{"shadeIds":[12698,29949,51237,31070,13031,245,58703,16997,60222,63890],"shadeData":[{"id":12698,"name":"TWFzdGVyIENsb3NldCBTaGFkZQ==","roomId":49106,"groupId":12777,"order":0,"type":18,"batteryStrength":175,"batteryStatus":3},{"id":29949,"name":"R3Vlc3QgQmVkcm9vbSBGcm9udCBTaGFkZQ==","roomId":64040,"groupId":57748,"order":1,"type":18,"batteryStrength":175,"batteryStatus":3},{"id":51237,"name":"T2ZmaWNlIFNoYWRl","roomId":24600,"groupId":26203,"order":2,"type":18,"batteryStrength":175,"batteryStatus":3},{"id":31070,"name":"TGl2aW5nIFJvb20gTGVmdCBTaGFkZQ==","roomId":22215,"groupId":44316,"order":3,"type":18,"batteryStrength":174,"batteryStatus":3, "positions":{"position1":65535,"posKind1":1}},{"id":13031,"name":"R3Vlc3QgQmVkcm9vbSBTaWRlIFNoYWRl","roomId":64040,"groupId":57748,"order":4,"type":18,"batteryStrength":176,"batteryStatus":3},{"id":245,"name":"TGl2aW5nIFJvb20gU2hlZXJz","roomId":22215,"groupId":58543,"order":5,"type":16,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":65535,"posKind1":1}},{"id":58703,"name":"THVrZSdzIFJvb20gU2hhZGU=","roomId":49867,"groupId":29368,"order":6,"type":18,"batteryStrength":0,"batteryStatus":0},{"id":16997,"name":"TGl2aW5nIFJvb20gUmlnaHQgU2hhZGU=","roomId":22215,"groupId":44316,"order":7,"type":18,"batteryStrength":174,"batteryStatus":3, "positions":{"position1":65535,"posKind1":1}},{"id":60222,"name":"TWFzdGVyIEJlZHJvb20gU2hhZGU=","roomId":48243,"groupId":25408,"order":8,"type":18,"batteryStrength":174,"batteryStatus":3},{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"batteryStrength":0,"batteryStatus":4}]}`

**Comment by Brklnbnc** [comment]
Testing the new plugin version now, but I'm experiencing the same issue, also with a Gen.1 version hub. I've quickly fixed this by commenting out the specific line in the index.js file.

**Comment by keybuk** [comment]
I pushed a speculative fix for this an hour or so ago: https://github.com/keybuk/homebridge-powerview/commit/4cb2024aca9a0288512776a33a43d5f37038f77c

Try updating and see if that's sufficient

**Comment by keybuk** [comment]
@samwelnella it looks like that fix should be enough to get the plugin running…

Could you give me a bit more details about the specific shades you have, to make sure they're supported - the plugin will treat them all like roller shades at the moment

**Comment by samwelnella** [comment]
@keybuk That fix took care of the initial issue but now I'm getting another issue. It might be related to the type of blinds I have. I'm gonna open up another issue for that.

I have Silhouette shades and Luminette sheers.

**Comment by keybuk** [comment]
Marking this one as fixed, please continue to open issues for any problems!
