### ISSUE TITLE
Unknown shades: 16, 18

### ISSUE THREAD

**Issue by samwelnella** [keybuk/homebridge-powerview#4]
I'm getting this error when adding shades of an unknown type. I believe the unknown shade is a Luminette sheer. Any ideas?

`Apr 24 16:08:56 nuc-homebridge homebridge[3921]: [2018-4-24 16:08:56] [PowerView] Hub: Home
Apr 24 16:08:56 nuc-homebridge homebridge[3921]: [2018-4-24 16:08:56] [PowerView] Adding shade 12698: Master Closet Shade
Apr 24 16:08:56 nuc-homebridge homebridge[3921]: [2018-4-24 16:08:56] [PowerView] Unknown shade type 18, assuming roller
Apr 24 16:08:56 nuc-homebridge homebridge[3921]: /usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:74
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:   dns_sd.DNSServiceUpdateRecord(this.serviceRef, null, 0, txtRecord, 0);
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:          ^
Apr 24 16:08:56 nuc-homebridge homebridge[3921]: Error: dns service error: no such name
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Advertisement.updateTXTRecord (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:74:10)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Advertiser.updateAdvertisement (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:73:25)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Bridge.Accessory._updateConfiguration (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:655:22)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:293:8)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:451:16)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at API.emit (events.js:180:13)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at PowerViewPlatform.addShadeAccessory (/usr/lib/node_modules/homebridge-powerview/index.js:112:11)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at PowerViewPlatform.<anonymous> (/usr/lib/node_modules/homebridge-powerview/index.js:294:33)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at PowerViewHub.<anonymous> (/usr/lib/node_modules/homebridge-powerview/PowerViewHub.js:100:18)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Request.self.callback (/usr/lib/node_modules/homebridge-powerview/node_modules/request/request.js:186:22)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Request.emit (events.js:180:13)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-powerview/node_modules/request/request.js:1163:10)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Request.emit (events.js:180:13)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-powerview/node_modules/request/request.js:1085:12)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at Object.onceWrapper (events.js:272:13)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at IncomingMessage.emit (events.js:185:15)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at endReadableNT (_stream_readable.js:1106:12)
Apr 24 16:08:56 nuc-homebridge homebridge[3921]:     at process._tickCallback (internal/process/next_tick.js:178:19)
`

**Comment by keybuk** [comment]
Yeah that was why I was pre-asking you for more information about your shades in the previous bug ;-)

Do these shades just go up and down, or do they have tillable vanes in the normal PowerView app?

**Comment by samwelnella** [comment]
Ah sorry, didn't want to clutter up the previous issue. These shades part in the middle and each half moves to the right and the left to open. They also have tiltable vertical vanes.

**Comment by keybuk** [comment]
Sorry, but can you be more specific?

You seem to have two different types of shade in your home, so it would be very useful to know which is which; and what you can do with them in the PowerView app.

```
Master Closet Shade            12698 18
Guest Bedroom Front Shade      29949 18
Office Shade                   51237 18
Living Room Left Shade         31070 18
Guest Bedroom Side Shade       13031 18
Living Room Sheers               245 16
Luke's Room Shade              58703 18
Living Room Right Shade        16997 18
Master Bedroom Shade           60222 18
Master Bedroom Sheers          63890 16
```

Can you also provide the output of the following commands for me:

```
curl http://powerview-hub.local/api/shades/245?refresh=true
```

```
curl http://powerview-hub.local/api/shades/31070?refresh=true
```

Thanks!

**Comment by samwelnella** [comment]
Sure. 245, and 63890 are Luminette sheers. With these I can both open and tilt them in the PowerView app. I've attached a screenshot in the PowerView app to show you exactly what I mean. 
![img_4498](https://user-images.githubusercontent.com/1754179/39212920-203c0354-47de-11e8-9ffb-ea7db94ac3e1.PNG)

All the other shades are Silhouette Shades which move up and down and have horizontal tiltable vanes. According to the readme these are already supported in the plugin.

Output of `curl http://powerview-hub.local/api/shades/245?refresh=true`:
`{"shade":{"id":245,"name":"TGl2aW5nIFJvb20gU2hlZXJz","roomId":22215,"groupId":58543,"order":5,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":65535,"posKind1":1}}}`

Output of `curl http://powerview-hub.local/api/shades/31070?refresh=true`
`{"shade":{"id":31070,"name":"TGl2aW5nIFJvb20gTGVmdCBTaGFkZQ==","roomId":22215,"groupId":44316,"order":3,"type":18,"timedOut":false,"batteryStrength":174,"batteryStatus":3, "positions":{"position1":65535,"posKind1":1}}}`

Thanks again for your help!

**Comment by keybuk** [comment]
Thanks, could you help grab a bit of data for those master bedroom sheers:

Before and after each step, can you run this and grab the output:

```
curl http://powerview-hub.local/api/shades/63890?refresh=true
```

Steps:

 1. Use the PowerView app to open the shades fully.
 2. Use the PowerView app to partially close the shades.
 3. Use the PowerView app to close the shades, but leave the vanes vertically.
 4. Use the PowerView app to partially tilt the vanes.
 5. Use the PowerView app to fully tilt the vanes to closed.

Do you know if it's possible with these shades to have them partially open, but with the vanes tilted? Or do the vanes always return to their mid tilt when you do that?

Thanks!

**Comment by samwelnella** [comment]
I forgot to mention that these sheers can tilt closed to either the right or the left. I added two additional steps at the end to tilt the shades to the left partially and fully (left and right directions are as seen in the PowerView app vane control)

Before step 1

`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":32768,"posKind1":3}}}`

After opening shades fully

`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":65535,"posKind1":1}}}`

After partially closing shades
`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":30972,"posKind1":1}}}`

After closing shades without touching vane control
`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":32768,"posKind1":3}}}`

After partially tilting vanes to the right
`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":20023,"posKind1":3}}}`

After fully tilting vanes closed to the right
`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":0,"posKind1":1}}}`

After partially tilting vanes to the left
`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":48896,"posKind1":3}}}`

After fully tilting vanes closed to the left
`{"shade":{"id":63890,"name":"TWFzdGVyIEJlZHJvb20gU2hlZXJz","roomId":48243,"groupId":18241,"order":9,"type":16,"timedOut":false,"batteryStrength":0,"batteryStatus":4, "positions":{"position1":48896,"posKind1":3}}}`

**Comment by keybuk** [comment]
Thanks, I'm still not quite visualizing how these work… I'll try and describe with ASCII art:

When the shades are fully open, do they look like this:
```
||  ||
```

Or like this?
```
=  =
```

When they're partially open, do they look like this?
```
| |   | |
```

Or like this?
```
- -   - -
```

When they're "closed" without vane control, do they look like:
```
| | | |
```

Or
```
----
```

I think I know, but I want to be sure…

When you "tilt to the right" does this mean they go"
```
| | | |   →    / / / /   →   ----
```

And "tilt to the left means:
```
| | | |   →   \ \ \ \   →   ----
```

Or are those the other way around? Best way to visualize, does the side of the vane closest to the window move left or right?

Thanks!

**Comment by samwelnella** [comment]
I'm assuming these ASCII art representations are top-down views? If so then:

When the shades are fully open they look like this:
`||  ||`

When the shades are partially open they look this:
`| |   | |`

When the shades are closed without vane control they look this this:
`| | | |`

Tilt to the right means:
`| | | |   →   \ \ \ \   →   ----`

Tilt to the left means:
`| | | |   →    / / / /   →   ----`

**Comment by keybuk** [comment]
Great, thanks!

Okay… give the current git version a try; that should recognize your luminette shades as ones with a vertical tilt.

Moving the shade up/down as usual should open them and close them, with "closed" and "open" matching what they actually do.

Under Details you can then access the vertical tilt slider. which should allow you to set values from -90 to 90.  -90 should swing your shades to the left, and +90 should swing your shades to the right.

Rules for scenes are a little weird, but basically:
 - if you set the tilt to 0 (the default), the open/closed slider takes effect
 - if you set the tilt to anything else, the open/closed slider gets ignored since the shades have to close to do it


If that all works, can you also check your pirouette shades - right now the slider does say -90 to 90, but I think only 0-90 works - do those move your shades as you'd expect?

Thanks!

**Comment by samwelnella** [comment]
Still having the same issue. I'm starting to think this issue:

`Apr 24 16:08:56 nuc-homebridge homebridge[3921]: /usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:74 Apr 24 16:08:56 nuc-homebridge homebridge[3921]: dns_sd.DNSServiceUpdateRecord(this.serviceRef, null, 0, txtRecord, 0); Apr 24 16:08:56 nuc-homebridge homebridge[3921]: ^ Apr 24 16:08:56 nuc-homebridge homebridge[3921]: Error: dns service error: no such name`

might be related to something else other than unknown shades.

**Comment by keybuk** [comment]
39822b86a7be78cea58e73f42e140bc9d469f9da should correct the crash for the others - but the bogus values will still be there, we'll come back to these in a moment

**Comment by samwelnella** [comment]
Okay here is the log for the Luminette sheers.
[PowerView.log](https://github.com/keybuk/homebridge-powerview/files/1945238/PowerView.log)

I can confirm that commanding the sheers to open sets the tilt back to 0 before opening.

**Comment by keybuk** [comment]
Oops, f479676d21fea83e2c5d5886b92cf09a48ead11f should fix the shades going the wrong way at -90

**Comment by samwelnella** [comment]
That fixed it!

**Comment by keybuk** [comment]
Great, thanks for all your help so far!

Let's swing back to those horizontal Pirouette shades now. Can you confirm that there's no crash now?

I'm assuming that the vanes are normally in the "open" (0 degrees) position when they move up and down? And in the PowerVIew app, they can just move from that to 90 degrees (effectively closed)

Is that right? Or do yours do a full -90 to 0 to +90 in the PowerView app?

**Comment by samwelnella** [comment]
There is no crash now. In the PowerView app they move from 0 to 90.

**Comment by keybuk** [comment]
One last thing to try: a24aa2c5b26bcdbe70a0d6d7ba1185f23a6e5ece

This should actually change the slider for the horizontal shades so it only goes from 0 to 90

**Comment by samwelnella** [comment]
Working good. Trying to set the slider below 0 gives an error and resets back to the previous tilt.

**Comment by keybuk** [comment]
Hmm, does the slider go below 0? For me that actually changed the slider so the far left position was 0

**Comment by samwelnella** [comment]
Ah I was using a third part home app which still has the slider going from -90 to 90. Using the Apple Home app shows the slider going only from 0-90.

**Comment by keybuk** [comment]
Sweet, so sounds like everything is working now?

**Comment by samwelnella** [comment]
Mostly. Last issue is on restarting Homebridge some of the shades show no response in the Apple Home app. In my third party Home app the "Current Position" characteristic and/or the "Current Horizontal/Vertical Tilt Angle" shows "Error" instead of the actual position/tilt. I need to use the third party Home app (control is not possible in the Apple Home app when the position or tilt shows an error) and move the shades initially to remove the error. Any ideas there?

**Comment by keybuk** [comment]
I think I know what might be causing that; can you kill the Home.app, and restart Homebridge, then grab the log from the restart for me through to the point where the Home app gives up after you relaunch it?

**Comment by samwelnella** [comment]
Gives up after I relaunch it? What do you mean by that? You mean when it shows no response for the blinds?

**Comment by keybuk** [comment]
Yeah, after you restart Homebridge, and relaunch the Home.app, it should say "Updating…" for a short period before eventually declaring "No Response"

If you can grab a log up to this point, that would be useful

**Comment by keybuk** [comment]
My guess from that log is that the Gen 1 hub misses out the positions list entirely when it's feeling uncooperative, which I was treating as an error - the Gen 2 returns an empty list instead.

465eb22a2803c1adb18c2fe4b1ca3c3308781395 should give you the same behavior - which is to force a refresh with the shade

**Comment by samwelnella** [comment]
That fixed it. The shades went from "No Response" to "Updating" to the correct values.

Thanks again for your time and effort helping with these issues. I really appreciate it.

**Comment by keybuk** [comment]
No, thank you for all your help debugging!

This is just something I hacked together for my own home, so it's great if others find it useful - and the more people it works for, the better!

Any other issues before I close this one out and send a new version to npm?

**Comment by samwelnella** [comment]
No more issues. I think it's safe to publish.

**Comment by keybuk** [comment]
Thanks for all your help!
