### ISSUE TITLE
If I adjust blinds with remote position isn't reflected in home kit.

### ISSUE THREAD

**Issue by djensenius** [keybuk/homebridge-powerview#6]

**Comment by keybuk** [comment]
This is actually a problem with the PowerView hub itself. The remote talks directly to the shades, and the hub caches values between operations so never sees that the shade has moved.

The plugin can force the hub to contact your shades for each update, but this will reduce the battery life of your shade.

Add the following to your config.json:

    refreshShades: true

**Comment by rxin** [comment]
I solved the issue by pairing the remote with the hub. Before I did that, hubs value don't get updated when the remote is used.
