### ISSUE TITLE
Unknown type 62 - Horizontal Shades without minValue of 0

### ISSUE THREAD

**Issue by githhw** [keybuk/homebridge-powerview#8]
I get the error "Shade has unknown type 62". 

The product I use is a horizontal blind (https://www.luxaflex.nl/producten/horizontale-jaloezieen/). The vanes can tilt from -90 to 90 degrees, so they work best with the ForceVerticalShades setting at the moment.

**Comment by keybuk** [comment]
Oh interesting, I'll have to add a new shade category for these

**Comment by khit** [comment]
Per #13, I also have horizontal slats (Unknown Type 40) with a tilt range from -90 to 90 degrees. So, these would benefit from this update too. (Currently using the ForceVerticalShades setting to address the full range.)

**Comment by keybuk** [comment]
I recommend using the new built-in HomeKit support
